"""add_email_to_rides

Revision ID: 366ae89e624f
Revises: 2c6dd00cc1e7
Create Date: 2026-04-23 16:30:06.120771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366ae89e624f'
down_revision: Union[str, None] = '2c6dd00cc1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'email')
    # ### end Alembic commands ###
