"""dispatcher_upgrades

Revision ID: dc2b35d0ef99
Revises: e251fb62b74c
Create Date: 2026-04-23 17:38:34.207873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2b35d0ef99'
down_revision: Union[str, None] = 'e251fb62b74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ride_status ADD VALUE IF NOT EXISTS 'cancelled'")
    op.execute("ALTER TYPE ride_status ADD VALUE IF NOT EXISTS 'no_show'")
    
    ride_priority = sa.dialects.postgresql.ENUM('low', 'normal', 'urgent', name='ride_priority')
    ride_priority.create(op.get_bind(), checkfirst=True)
    
    op.add_column('rides', sa.Column('priority', ride_priority, server_default='normal', nullable=False))
    op.add_column('rides', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'updated_at')
    op.drop_column('rides', 'priority')
    # ### end Alembic commands ###
