"""add_form_fields_to_rides

Revision ID: e251fb62b74c
Revises: 366ae89e624f
Create Date: 2026-04-23 17:24:16.393159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e251fb62b74c'
down_revision: Union[str, None] = '366ae89e624f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('rides', sa.Column('alt_phone', sa.String(length=30), nullable=True))
    op.add_column('rides', sa.Column('requested_pickup_time', sa.String(length=10), nullable=True))
    op.add_column('rides', sa.Column('return_trip', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rides', sa.Column('mobility_needs', sa.String(length=100), nullable=True))
    op.add_column('rides', sa.Column('recurring', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'recurring')
    op.drop_column('rides', 'mobility_needs')
    op.drop_column('rides', 'return_trip')
    op.drop_column('rides', 'requested_pickup_time')
    op.drop_column('rides', 'alt_phone')
    op.drop_column('rides', 'date_of_birth')
    # ### end Alembic commands ###
